---
name: App-ZofCMS-Plugin-HTMLFactory
version: 0.0102
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: 'notes for modules in App::ZofCMS::Plugin::HTMLFactory:: namespace'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::HTMLFactory:
    file: lib/App/ZofCMS/Plugin/HTMLFactory.pm
    version: 0.0102
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
